# Generated by Django 6.0.2 on 2026-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transactioncategory_transactiontype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='saldo_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo real declarado manualmente por el usuario', max_digits=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='Nombre de la cuenta (ej: Caja, Bancolombia, Nequi)', max_length=100),
        ),
    ]
